### ISSUE TITLE
Issue with adding a BD => move_uploaded_file(assets/images/comicUpload/6278cb12cbecb-2B391DE7-3005-4A5F-8503-7055BCBDCF51_1_105_c.jpeg): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by CelieRussier** [WildCodeSchool/2022_03_PHP_Lyon_P2_Comic_Cult#48]
<img width="1428" alt="Capture d’écran 2022-05-09 à 10 05 20" src="https://user-images.githubusercontent.com/91675494/167367210-664204bf-bbc3-4672-b4d1-3f16f030e5a8.png">
<img width="1428" alt="Capture d’écran 2022-05-09 à 10 06 38" src="https://user-images.githubusercontent.com/91675494/167367214-b3d6f183-8f28-430b-b0e9-ee622330f512.png">

**Comment by Anthony-AGTN** [comment]
Meme erreur de mon côté, car le dossier "assets/images/comicUpload/" n'existe pas dans le projet.

**Comment by vincentDubresson** [comment]
This issue is fixed by creating an empty file in this folder in order to have the folder even if there is no picture.
