### ISSUE TITLE
Issue with "return_button"

### ISSUE THREAD

**Issue by Alphapwned** [WildCodeSchool/2022_03_PHP_Lyon_P2_Comic_Cult#49]
Issue : When I'm on " http://localhost:8000/admin/list ", I want to edit something, so I do it.
Finaly, when I'm on " http://localhost:8000/admin/edit?id=2 " (for exemple), I don't want to edit and I juste want to come back on the list.
If I use the return_button, I'm going on " http://localhost:8000/admin/author " and not on the page where I've been before ( http://localhost:8000/admin/list ).

**Comment by vincentDubresson** [comment]
This issue is fixed ! Thank you !
