### ISSUE TITLE
petit manque de padding ou margin en bas de page à l'affichage de la liste des résultats qd réduction de la fenêtre du navigateur

### ISSUE THREAD

**Issue by CelieRussier** [WildCodeSchool/2022_03_PHP_Lyon_P2_Comic_Cult#50]
idem à l'affichage du détail de la bd.

<img width="1440" alt="Capture d’écran 2022-05-09 à 10 34 17" src="https://user-images.githubusercontent.com/91675494/167371928-95ad9feb-2318-4969-86a6-70af670feb9f.png">

<img width="1440" alt="Capture d’écran 2022-05-09 à 10 32 54" src="https://user-images.githubusercontent.com/91675494/167371910-0c3c9c2f-6514-4fc4-816d-57a2c583945a.png">

**Comment by vincentDubresson** [comment]
This issue is fixed. Thank you !
