### ISSUE TITLE
Je peux ajouter un Auteur qui n'est pas encore né ou qui va naitre en 2056

### ISSUE THREAD

**Issue by Anthony-AGTN** [WildCodeSchool/2022_03_PHP_Lyon_P2_Comic_Cult#51]
![image](https://user-images.githubusercontent.com/60406557/167373711-08a3c497-36c9-41cb-8cfb-21b53e23746a.png)

**Comment by vincentDubresson** [comment]
This issue is fixed for author creation and author edition. Thanks for review !
