### ISSUE TITLE
Erreur JS sur les pages contact, /admin/list, /admin/author et /admin/contact

### ISSUE THREAD

**Issue by Anthony-AGTN** [WildCodeSchool/2022_03_PHP_Lyon_P2_Comic_Cult#54]
J'ai une erreur JS qui apparaît lors de l'ouverture des pages contact, /admin/list, /admin/author et /admin/contact.

Sur >>> let section = firstActive.children[1].querySelector("p");

Uncaught TypeError: Cannot read properties of null (reading 'children')
    at window.onload (script.js:19:29)
window.onload @ script.js:19
load (asynchrone)
(anonyme) @ script.js:14

![image](https://user-images.githubusercontent.com/60406557/167505041-6da8764d-8474-4a4b-aa8b-8cd1ead8ca5e.png)

**Comment by vincentDubresson** [comment]
Issue fixed. Thank you !
